"""initial schema

Revision ID: c6ff0df5c965
Revises:
Create Date: 2026-05-25 00:36:25.133763

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6ff0df5c965"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.create_index("ix_ingestion_runs_status", ["status"], unique=False)

    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_model_versions_name_version"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index("ix_teams_code", ["code"], unique=False)

    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index("ix_games_away_team_id", ["away_team_id"], unique=False)
        batch_op.create_index("ix_games_game_date", ["game_date"], unique=False)
        batch_op.create_index("ix_games_home_team_id", ["home_team_id"], unique=False)

    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("position", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index("ix_players_external_id", ["external_id"], unique=False)
        batch_op.create_index("ix_players_team_id", ["team_id"], unique=False)

    op.create_table(
        "stat_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stat_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stat_snapshots_ingestion_run_id", ["ingestion_run_id"], unique=False
        )
        batch_op.create_index("ix_stat_snapshots_snapshot_at", ["snapshot_at"], unique=False)

    op.create_table(
        "actual_lineup_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_id",
            "team_id",
            "announced_at",
            name="uq_actual_lineup_snapshots_game_team_announced",
        ),
    )
    with op.batch_alter_table("actual_lineup_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_actual_lineup_snapshots_announced_at", ["announced_at"], unique=False
        )
        batch_op.create_index("ix_actual_lineup_snapshots_game_id", ["game_id"], unique=False)
        batch_op.create_index("ix_actual_lineup_snapshots_team_id", ["team_id"], unique=False)
        batch_op.create_index(
            "ix_actual_lineup_snapshots_ingestion_run_id", ["ingestion_run_id"], unique=False
        )

    op.create_table(
        "box_score_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("box_score_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_box_score_snapshots_game_id", ["game_id"], unique=False)
        batch_op.create_index(
            "ix_box_score_snapshots_ingestion_run_id", ["ingestion_run_id"], unique=False
        )
        batch_op.create_index("ix_box_score_snapshots_taken_at", ["taken_at"], unique=False)

    op.create_table(
        "player_stat_snapshot_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("stats_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["stat_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("player_stat_snapshot_rows", schema=None) as batch_op:
        batch_op.create_index("ix_player_stat_snapshot_rows_player_id", ["player_id"], unique=False)
        batch_op.create_index(
            "ix_player_stat_snapshot_rows_snapshot_id", ["snapshot_id"], unique=False
        )

    op.create_table(
        "actual_lineup_snapshot_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("batting_order", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["actual_lineup_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("actual_lineup_snapshot_rows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_actual_lineup_snapshot_rows_player_id", ["player_id"], unique=False
        )
        batch_op.create_index(
            "ix_actual_lineup_snapshot_rows_snapshot_id", ["snapshot_id"], unique=False
        )

    op.create_table(
        "box_score_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("at_bats", sa.Integer(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("runs", sa.Integer(), nullable=True),
        sa.Column("rbis", sa.Integer(), nullable=True),
        sa.Column("extra_stats_json", sa.JSON(), nullable=True),
        sa.Column("innings_pitched", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["box_score_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("box_score_rows", schema=None) as batch_op:
        batch_op.create_index("ix_box_score_rows_player_id", ["player_id"], unique=False)
        batch_op.create_index("ix_box_score_rows_snapshot_id", ["snapshot_id"], unique=False)

    op.create_table(
        "lineup_evaluation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("stat_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("lineup_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("evaluation_cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_manifest_json", sa.JSON(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("model_config_json", sa.JSON(), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lineup_snapshot_id"],
            ["actual_lineup_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stat_snapshot_id"],
            ["stat_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_id",
            "team_id",
            "evaluation_cutoff_at",
            "stat_snapshot_id",
            "lineup_snapshot_id",
            "model_version_id",
            name="uq_lineup_evaluation_runs_idempotency",
        ),
    )
    with op.batch_alter_table("lineup_evaluation_runs", schema=None) as batch_op:
        batch_op.create_index("ix_lineup_evaluation_runs_game_id", ["game_id"], unique=False)
        batch_op.create_index("ix_lineup_evaluation_runs_status", ["status"], unique=False)
        batch_op.create_index("ix_lineup_evaluation_runs_team_id", ["team_id"], unique=False)

    op.create_table(
        "lineup_evaluation_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_run_id", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("key_insights_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["lineup_evaluation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_run_id"),
    )
    with op.batch_alter_table("lineup_evaluation_summaries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lineup_evaluation_summaries_run_id", ["evaluation_run_id"], unique=False
        )

    op.create_table(
        "postgame_review_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_run_id", sa.Integer(), nullable=False),
        sa.Column("box_score_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_manifest_json", sa.JSON(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("model_config_json", sa.JSON(), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["box_score_snapshot_id"],
            ["box_score_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["lineup_evaluation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("postgame_review_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_postgame_review_runs_box_score_snapshot_id", ["box_score_snapshot_id"], unique=False
        )
        batch_op.create_index(
            "ix_postgame_review_runs_evaluation_run_id", ["evaluation_run_id"], unique=False
        )
        batch_op.create_index("ix_postgame_review_runs_status", ["status"], unique=False)

    op.create_table(
        "recommended_lineup_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_run_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("batting_order", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=8), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["lineup_evaluation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommended_lineup_rows", schema=None) as batch_op:
        batch_op.create_index("ix_recommended_lineup_rows_player_id", ["player_id"], unique=False)
        batch_op.create_index(
            "ix_recommended_lineup_rows_run_id", ["evaluation_run_id"], unique=False
        )

    op.create_table(
        "postgame_review_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_run_id", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("comparison_json", sa.JSON(), nullable=True),
        sa.Column("accuracy_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_run_id"],
            ["postgame_review_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_run_id"),
    )
    with op.batch_alter_table("postgame_review_summaries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_postgame_review_summaries_review_run_id", ["review_run_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("postgame_review_summaries", schema=None) as batch_op:
        batch_op.drop_index("ix_postgame_review_summaries_review_run_id")

    op.drop_table("postgame_review_summaries")
    with op.batch_alter_table("recommended_lineup_rows", schema=None) as batch_op:
        batch_op.drop_index("ix_recommended_lineup_rows_run_id")
        batch_op.drop_index("ix_recommended_lineup_rows_player_id")

    op.drop_table("recommended_lineup_rows")
    with op.batch_alter_table("postgame_review_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_postgame_review_runs_status")
        batch_op.drop_index("ix_postgame_review_runs_evaluation_run_id")
        batch_op.drop_index("ix_postgame_review_runs_box_score_snapshot_id")

    op.drop_table("postgame_review_runs")
    with op.batch_alter_table("lineup_evaluation_summaries", schema=None) as batch_op:
        batch_op.drop_index("ix_lineup_evaluation_summaries_run_id")

    op.drop_table("lineup_evaluation_summaries")
    with op.batch_alter_table("lineup_evaluation_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_lineup_evaluation_runs_team_id")
        batch_op.drop_index("ix_lineup_evaluation_runs_status")
        batch_op.drop_index("ix_lineup_evaluation_runs_game_id")

    op.drop_table("lineup_evaluation_runs")
    with op.batch_alter_table("box_score_rows", schema=None) as batch_op:
        batch_op.drop_index("ix_box_score_rows_snapshot_id")
        batch_op.drop_index("ix_box_score_rows_player_id")

    op.drop_table("box_score_rows")
    with op.batch_alter_table("actual_lineup_snapshot_rows", schema=None) as batch_op:
        batch_op.drop_index("ix_actual_lineup_snapshot_rows_snapshot_id")
        batch_op.drop_index("ix_actual_lineup_snapshot_rows_player_id")

    op.drop_table("actual_lineup_snapshot_rows")
    with op.batch_alter_table("player_stat_snapshot_rows", schema=None) as batch_op:
        batch_op.drop_index("ix_player_stat_snapshot_rows_snapshot_id")
        batch_op.drop_index("ix_player_stat_snapshot_rows_player_id")

    op.drop_table("player_stat_snapshot_rows")
    with op.batch_alter_table("box_score_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_box_score_snapshots_taken_at")
        batch_op.drop_index("ix_box_score_snapshots_ingestion_run_id")
        batch_op.drop_index("ix_box_score_snapshots_game_id")

    op.drop_table("box_score_snapshots")
    with op.batch_alter_table("actual_lineup_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_actual_lineup_snapshots_ingestion_run_id")
        batch_op.drop_index("ix_actual_lineup_snapshots_team_id")
        batch_op.drop_index("ix_actual_lineup_snapshots_game_id")
        batch_op.drop_index("ix_actual_lineup_snapshots_announced_at")

    op.drop_table("actual_lineup_snapshots")
    with op.batch_alter_table("stat_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_stat_snapshots_snapshot_at")
        batch_op.drop_index("ix_stat_snapshots_ingestion_run_id")

    op.drop_table("stat_snapshots")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index("ix_players_team_id")
        batch_op.drop_index("ix_players_external_id")

    op.drop_table("players")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index("ix_games_home_team_id")
        batch_op.drop_index("ix_games_game_date")
        batch_op.drop_index("ix_games_away_team_id")

    op.drop_table("games")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index("ix_teams_code")

    op.drop_table("teams")
    op.drop_table("model_versions")
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_ingestion_runs_status")

    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
