name: test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  api:
    name: api pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run pytest
        run: cd apps/api && uv run pytest
